version: "3.2"
services:
  editor_app:
    image: registry.cn-zhangjiakou.aliyuncs.com/bisheng/editor_app_arm:${tag}
    container_name: editor_app
    privileged: true
    volumes:
    - ${basedir}/workspace:/workspace
    restart: on-failure:10
    environment:
      NODEID: editor_app_worker
#    ports:
#    - 5500:5500
    networks:
      bisheng:
        aliases:
        - editor_app
  editor:
    image: registry.cn-zhangjiakou.aliyuncs.com/bisheng/editor_arm:${tag}
    container_name: editor
    privileged: true
    volumes:
    - ${basedir}/workspace:/workspace
    restart: on-failure:10
    environment:
      ADDR: editor
      NODEID: editor_worker
  convert:
    image: registry.cn-zhangjiakou.aliyuncs.com/bisheng/convert_arm:${tag}
    container_name: convert
    privileged: true
    volumes:
    - ${basedir}/workspace:/workspace
    restart: on-failure:10
    environment:
      ADDR: convert
      NODEID: convert_worker
    networks:
      bisheng:
        aliases:
        - convert
#    ports:
#    - 18000:18000
    networks:
      bisheng:
        aliases:
        - editor
networks:
  bisheng:
    external: true
